### ISSUE TITLE
Listing SSO identity providers raises an error

### ISSUE THREAD

**Issue by debussyman** [extragoodlabs/jumpwire#12]
Gateway raises an error when using `jwctl` to list auth providers.

Platform: Ubuntu 22.04 (WSL2)
JumpWire version: 3.1.0

Ran this command:
```shell
$ JW_URL=http://localhost:4004 jwctl auth list
```

Got this error in the gateway:
```shell
20:03:43.446 [error] #PID<0.3539.0> running JumpWire.Router (connection #PID<0.3538.0>, stream id 1) terminated
Server: localhost:4004 (http)
Request: GET /sso
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Jason.OrderedObject, List, Map, MapSet, MerkleMap, Postgrex.Stream, Range, Stream
        (elixir 1.14.5) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir 1.14.5) lib/enum.ex:166: Enumerable.reduce/3
        (elixir 1.14.5) lib/enum.ex:4307: Enum.map/2
        (jumpwire 3.1.0) lib/jumpwire/sso/router.ex:36: anonymous fn/2 in JumpWire.SSO.Router.do_match/4
        (jumpwire 3.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in JumpWire.SSO.Router.dispatch/2
        (telemetry 0.4.3) /app/deps/telemetry/src/telemetry.erl:272: :telemetry.span/3
        (jumpwire 3.1.0) deps/plug/lib/plug/router.ex:242: JumpWire.SSO.Router.dispatch/2
        (jumpwire 3.1.0) lib/jumpwire/sso/router.ex:1: JumpWire.SSO.Router.plug_builder_call/2
```

**Comment by hexedpackets** [comment]
This is with no IdPs configured (eg the default setup)?
